
import React, { useState } from 'react';
import { DLAReport } from '../types';
import { 
  FileText, Printer, ShieldCheck, HardHat, AlertTriangle, CheckCircle, 
  TrendingDown, TrendingUp, DollarSign, Clock, Timer, BookOpen, Cpu,
  MessageSquare, Keyboard, Briefcase, Info, X, Calculator, Code, 
  ChevronDown, ChevronUp, Fingerprint, Activity, Terminal, Download, ArrowUpRight
} from 'lucide-react';

interface DLAResultProps {
  report: DLAReport;
}

const DLAResult: React.FC<DLAResultProps> = ({ report }) => {
  const { calculations, inputRequest, watermark, timestamp, promptTitle } = report;
  const { 
    trueNetValue, grossLaborValue, hiddenFrictionCost, manualMinutes, 
    waitCost, readingCost, fixingCost, isProfitable, arbitrageEfficiency
  } = calculations;

  const [inspectedMetric, setInspectedMetric] = useState<string | null>(null);
  const [showAlgorithm, setShowAlgorithm] = useState(false);

  const formatMoney = (amount: number) => 
    new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount);

  const formatPercent = (val: number) => `${(val * 100).toFixed(1)}%`;

  const totalComparisonValue = grossLaborValue + hiddenFrictionCost;
  const valuePercentage = totalComparisonValue > 0 ? (grossLaborValue / totalComparisonValue) * 100 : 0;

  const metricDetails: Record<string, { title: string, formula: string, logic: string }> = {
    gross: {
      title: "Gross Labor Value",
      formula: "((Chars / 5) / WPM) * (Hourly Wage / 60)",
      logic: "Calculates the baseline cost of a human performing the task manually at specified production speeds based on word count physics."
    },
    friction: {
      title: "Hidden Friction Cost",
      formula: "WaitCost + ReadingCost + FixingCost + APICost",
      logic: "The sum total of operational overhead and 'Interaction Taxes' generated by using AI instead of full manual production."
    },
    latency: {
      title: "Latency Cost (Wait)",
      formula: "(API Latency / 60) * (Hourly Wage / 60)",
      logic: "The financial cost of an operator's idle time while waiting for the model's token generation stream."
    },
    fix: {
      title: "Correction Tax",
      formula: "(Edit Time / 60) * (Hourly Wage / 60)",
      logic: "The labor overhead required for manual review, fact-checking, and formatting adjustments to the model output."
    }
  };

  const pythonImplementation = `
def calculate_dla(output_chars, latency_sec, edit_sec, api_cost, human_wpm, human_read_wpm, wage_hr):
    """
    DIFFERENTIAL LABOR ARBITRAGE (D.L.A.) CORE PROTOCOL
    Computes the deterministic financial delta between manual labor and AI friction.
    """
    CHARS_PER_WORD = 5
    MINUTE_RATE = wage_hr / 60
    
    # 1. ESTABLISH MANUAL BASELINE
    total_words = output_chars / CHARS_PER_WORD
    manual_minutes = total_words / human_wpm
    gross_labor_value = manual_minutes * MINUTE_RATE
    
    # 2. CALCULATE OPERATIONAL FRICTION (THE TAX)
    wait_cost = (latency_sec / 60) * MINUTE_RATE
    reading_cost = (total_words / human_read_wpm) * MINUTE_RATE
    fixing_cost = (edit_sec / 60) * MINUTE_RATE
    
    total_friction = wait_cost + reading_cost + fixing_cost + api_cost
    
    # 3. COMPUTE ARBITRAGE DELTA
    true_net_value = gross_labor_value - total_friction
    
    return {
        "true_net_value": round(true_net_value, 4),
        "is_profitable": true_net_value > 0,
        "arbitrage_efficiency": (true_net_value / gross_labor_value) if gross_labor_value > 0 else 0
    }
`.trim();

  const handleDownloadAsset = () => {
    const markdownContent = `
# KONKRED D.L.A. AUDIT REPORT
**ASSET:** ${promptTitle || 'Untitled Asset'}
**VERIFIED SESSION ID:** ${watermark}
**DATE:** ${timestamp}
**ARBITRAGE STATUS:** ${isProfitable ? 'POSITIVE' : 'NEGATIVE'}
**TRUE NET VALUE:** ${formatMoney(trueNetValue)}
**EFFICIENCY RATIO:** ${formatPercent(arbitrageEfficiency)}

## FINANCIAL BREAKDOWN
- **Gross Labor Value:** ${formatMoney(grossLaborValue)}
- **Hidden Friction Cost:** -${formatMoney(hiddenFrictionCost)}

## HIDDEN FRICTION COST BREAKDOWN
- **Latency (Wait) Cost:** ${formatMoney(waitCost)}
- **Reading (Verify) Cost:** ${formatMoney(readingCost)}
- **Fixing (Correction) Cost:** ${formatMoney(fixingCost)}
- **API Hard Cost:** ${formatMoney(inputRequest.apiCostUsd)}

## AUDIT PARAMETERS
- Output Size: ${inputRequest.outputCharCount} characters
- Human Wage: ${formatMoney(inputRequest.hourlyWage)}/hr
- AI Latency: ${inputRequest.apiLatencySeconds}s
- Correction Time: ${inputRequest.editSessionSeconds}s

## DETERMINISTIC LOGIC
This report measures displacement of linear manual labor cycles via interaction friction metrics. 
The resulting Delta represents the realized financial efficiency of the AI asset.
    `.trim();
    const blob = new Blob([markdownContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `KONKRED_DLA_AUDIT_${watermark}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };
  
  return (
    <div className="pb-12 space-y-8 font-mono relative animate-in slide-in-from-bottom-8 duration-700">
      
      {/* Metric Inspector Overlay */}
      {inspectedMetric && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-6 bg-black/80 backdrop-blur-md animate-in fade-in zoom-in-95 duration-200">
            <div className="bg-cyber-dark border border-cyber-cyan w-full max-w-lg p-8 rounded-sm shadow-neon-cyan relative">
                <button onClick={() => setInspectedMetric(null)} className="absolute top-4 right-4 text-slate-500 hover:text-white transition-colors"><X size={20}/></button>
                <div className="flex items-center gap-3 text-cyber-cyan mb-6">
                    <Calculator size={24} />
                    <h3 className="text-xl font-bold uppercase tracking-wider">{metricDetails[inspectedMetric].title}</h3>
                </div>
                <div className="bg-black p-5 border border-cyber-gray mb-6">
                    <p className="text-[10px] text-slate-500 uppercase mb-3 font-bold tracking-widest text-center">Protocol Mathematics</p>
                    <p className="text-lg text-white font-bold italic border-l-2 border-cyber-cyan pl-4">{metricDetails[inspectedMetric].formula}</p>
                </div>
                <p className="text-sm text-slate-400 leading-relaxed">{metricDetails[inspectedMetric].logic}</p>
            </div>
        </div>
      )}

      {/* Forensic Header */}
      <div className="bg-cyber-dark/40 border border-cyber-gray p-6 text-center rounded-sm relative overflow-hidden group">
        <div className="absolute inset-0 bg-grid-pattern opacity-5 group-hover:opacity-10 transition-opacity"></div>
        <div className="relative z-10">
            <div className="inline-flex items-center gap-2 mb-2 px-3 py-1 bg-cyber-cyan/10 border border-cyber-cyan/30 rounded-full text-[10px] text-cyber-cyan font-bold tracking-[0.2em] uppercase">
                <Activity size={10} className="animate-pulse" /> Financial Telemetry Handshake
            </div>
            <h2 className="text-white text-lg uppercase tracking-[0.4em] font-bold">Differential Labor Arbitrage Protocol</h2>
        </div>
      </div>
      
      {/* Profitability Diagnostic - HIGH VISIBILITY ENHANCEMENT */}
      <div className={`p-8 lg:p-10 border-l-8 ${isProfitable ? 'border-cyber-green bg-gradient-to-r from-cyber-green/20 to-black' : 'border-cyber-red bg-gradient-to-r from-cyber-red/20 to-black'} rounded-sm flex flex-col md:flex-row items-center gap-10 relative overflow-hidden shadow-2xl transition-all duration-500 hover:scale-[1.01]`}>
          <div className="absolute inset-0 bg-noise opacity-[0.03]"></div>
          
          <div className={`flex-shrink-0 w-32 h-32 rounded-full flex items-center justify-center border-4 ${isProfitable ? 'border-cyber-green text-cyber-green shadow-[0_0_30px_rgba(10,255,0,0.3)] bg-black' : 'border-cyber-red text-cyber-red shadow-[0_0_30px_rgba(255,42,42,0.3)] bg-black'} relative z-10 animate-in zoom-in-50 duration-700`}>
              {isProfitable ? <CheckCircle size={64} /> : <AlertTriangle size={64} />}
          </div>

          <div className="flex-1 text-center md:text-left relative z-10">
              <div className={`text-xs font-bold uppercase tracking-[0.2em] mb-2 ${isProfitable ? 'text-cyber-green' : 'text-cyber-red'}`}>
                  Arbitrage Verdict
              </div>
              <h3 className={`font-bold text-5xl uppercase tracking-tighter mb-4 ${isProfitable ? 'text-white text-glow-green' : 'text-white text-glow-red'}`}>
                {isProfitable ? "PROFITABLE" : "UNPROFITABLE"}
              </h3>
              <p className="text-sm text-slate-300 max-w-lg leading-relaxed border-l-2 border-slate-700 pl-4">
                  {isProfitable 
                    ? "Deployment Authorized. The asset generates significant surplus value by displacing manual labor at a rate higher than its operational friction." 
                    : "Deployment Caution. Operational friction costs (wait time, review, correction) currently exceed the value of the manual labor displaced."}
              </p>
          </div>

          <div className="flex flex-col gap-4 min-w-[240px] relative z-10">
            <div className="bg-black/80 p-6 border border-cyber-gray text-center rounded-sm backdrop-blur-md shadow-lg transform rotate-1">
                <div className="text-[10px] text-slate-400 uppercase tracking-widest mb-1 font-bold">True Net Value / Run</div>
                <div className={`text-4xl font-bold tracking-tighter ${isProfitable ? 'text-cyber-green' : 'text-cyber-red'}`}>
                    {formatMoney(trueNetValue)}
                </div>
            </div>
            
            <div className="bg-black/80 p-4 border border-cyber-gray text-center rounded-sm backdrop-blur-md shadow-lg transform -rotate-1">
                <div className="text-[10px] text-slate-400 uppercase tracking-widest mb-1 font-bold">Efficiency Ratio</div>
                <div className={`text-xl font-bold tracking-tighter ${arbitrageEfficiency > 0.5 ? 'text-cyber-cyan' : arbitrageEfficiency > 0 ? 'text-white' : 'text-cyber-red'}`}>
                    {formatPercent(arbitrageEfficiency)}
                </div>
            </div>
          </div>
      </div>

      {/* Valuation Physics Infographic */}
      <div className="bg-cyber-dark/40 border border-cyber-gray p-8 rounded-sm">
         <h3 className="text-[10px] text-slate-500 uppercase tracking-[0.3em] mb-8 text-center flex items-center justify-center gap-3">
            <div className="h-px w-12 bg-cyber-gray"></div>
            Valuation Physics: Gross vs. Friction
            <div className="h-px w-12 bg-cyber-gray"></div>
         </h3>
         
         <div className="space-y-8 max-w-4xl mx-auto">
            {/* Visual Bar Representation */}
            <div className="relative pt-6 pb-2">
                <div className="flex justify-between mb-2 font-mono text-xs font-bold uppercase">
                    <span className="text-cyber-green flex items-center gap-2"><TrendingUp size={14} /> Gross Labor Value</span>
                    <span className="text-cyber-red flex items-center gap-2">Hidden Friction Cost <TrendingDown size={14} /></span>
                </div>
                
                <div className="w-full h-20 bg-black border border-cyber-gray rounded-sm overflow-hidden flex relative shadow-inner">
                    <div className="absolute inset-0 bg-grid-pattern opacity-10"></div>
                    
                    {/* Gross Value Bar */}
                    <div className="h-full bg-gradient-to-r from-cyber-green/20 via-cyber-green/40 to-cyber-green/20 relative group/bar flex items-center justify-start pl-4 border-r border-cyber-green/50 transition-all duration-1000" style={{ width: `${valuePercentage}%` }}>
                        <span className="text-white font-bold text-lg drop-shadow-md z-10">{formatMoney(grossLaborValue)}</span>
                        <div className="absolute bottom-0 left-0 w-full h-1 bg-cyber-green"></div>
                    </div>
                    
                    {/* Friction Cost Bar */}
                    <div className="h-full bg-gradient-to-l from-cyber-red/20 via-cyber-red/40 to-cyber-red/20 flex items-center justify-end pr-4 border-l border-cyber-red/50 transition-all duration-1000" style={{ width: `${100 - valuePercentage}%` }}>
                        <span className="text-white font-bold text-lg drop-shadow-md z-10">-{formatMoney(hiddenFrictionCost)}</span>
                        <div className="absolute bottom-0 left-0 w-full h-1 bg-cyber-red"></div>
                    </div>
                </div>

                <div className="flex justify-center -mt-4 relative z-20">
                    <div className={`px-6 py-2 rounded-full text-sm font-bold uppercase tracking-wider border shadow-xl flex items-center gap-2 ${isProfitable ? 'bg-cyber-green text-black border-cyber-green shadow-neon-green' : 'bg-cyber-red text-white border-cyber-red shadow-neon-red'}`}>
                        {isProfitable ? <ArrowUpRight size={16} /> : <TrendingDown size={16} />}
                        Net: {formatMoney(trueNetValue)}
                    </div>
                </div>
            </div>

            {/* Detailed Row Data */}
            <div className="grid grid-cols-2 gap-4 pt-4 border-t border-cyber-gray/30">
                <div 
                    onClick={() => setInspectedMetric('gross')}
                    className="flex justify-between items-center text-sm cursor-pointer group p-3 hover:bg-white/5 rounded-sm transition-colors"
                >
                   <span className="font-bold text-slate-400 group-hover:text-cyber-green transition-colors">
                     Manual Baseline Value
                   </span>
                   <span className="font-bold text-white text-lg">{formatMoney(grossLaborValue)}</span>
                </div>
                <div 
                    onClick={() => setInspectedMetric('friction')}
                    className="flex justify-between items-center text-sm cursor-pointer group p-3 hover:bg-white/5 rounded-sm transition-colors"
                >
                   <span className="font-bold text-slate-400 group-hover:text-cyber-red transition-colors">
                     Operational Friction Tax
                   </span>
                   <span className="font-bold text-white text-lg">-{formatMoney(hiddenFrictionCost)}</span>
                </div>
            </div>
         </div>
      </div>

      {/* Hidden Friction Cost Breakdown */}
      <div className="bg-black/40 border border-cyber-gray p-8 rounded-sm">
        <h3 className="text-[10px] text-cyber-red uppercase tracking-widest flex items-center gap-2 font-bold mb-8">
            <Terminal size={14} /> Hidden Friction Cost Breakdown
        </h3>
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-8">
            {[
              { id: 'latency', label: "Wait Latency", value: waitCost, icon: <Timer size={24} />, max: hiddenFrictionCost, color: 'text-cyber-red' },
              { id: 'read', label: "Cognitive Verify", value: readingCost, icon: <BookOpen size={24} />, max: hiddenFrictionCost, color: 'text-cyber-orange' },
              { id: 'fix', label: "Correction Tax", value: fixingCost, icon: <HardHat size={24} />, max: hiddenFrictionCost, color: 'text-cyber-red' },
              { id: 'api', label: "API Hard Cost", value: inputRequest.apiCostUsd, icon: <Cpu size={24} />, max: hiddenFrictionCost, color: 'text-slate-400' },
            ].map(item => (
                <div 
                  key={item.label} 
                  onClick={() => item.id !== 'api' && setInspectedMetric(item.id)}
                  className={`flex flex-col items-center text-center p-4 rounded-sm border border-transparent hover:border-cyber-gray hover:bg-white/5 transition-all ${item.id !== 'api' ? 'cursor-pointer' : ''}`}
                >
                    <div className="relative w-20 h-20 mb-4">
                        <svg className="w-full h-full transform -rotate-90" viewBox="0 0 36 36">
                            <path d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke="#222" strokeWidth="3" />
                            <path className={item.color} d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke="currentColor" strokeWidth="3" strokeDasharray={`${(item.value / (item.max || 1)) * 100}, 100`} strokeLinecap="round" />
                        </svg>
                        <div className="absolute inset-0 flex items-center justify-center opacity-80">{item.icon}</div>
                    </div>
                    <p className="text-xl font-bold text-white mb-1">{formatMoney(item.value)}</p>
                    <p className="text-[9px] text-slate-500 uppercase tracking-widest font-bold">{item.label}</p>
                </div>
            ))}
        </div>
      </div>

      {/* Blueprint Transparency */}
      <div className="border border-cyber-gray bg-black/60 rounded-sm overflow-hidden">
        <button 
            onClick={() => setShowAlgorithm(!showAlgorithm)}
            className="w-full flex items-center justify-between p-5 hover:bg-white/5 transition-colors"
        >
            <div className="flex items-center gap-4">
                <div className="p-2 bg-cyber-green/10 rounded-sm">
                    <Code className="text-cyber-green" size={18} />
                </div>
                <div className="text-left">
                    <span className="text-xs uppercase font-bold tracking-widest text-white block">Audit Source Transparency</span>
                    <span className="text-[9px] text-slate-500 uppercase">View Core D.L.A. Algorithm Implementation</span>
                </div>
            </div>
            <div className="text-slate-500">
                {showAlgorithm ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
            </div>
        </button>
        {showAlgorithm && (
            <div className="p-6 border-t border-cyber-gray bg-black/80 animate-in slide-in-from-top-2 duration-300">
                <div className="flex justify-between items-center mb-4">
                    <div className="flex items-center gap-2">
                        <Terminal size={12} className="text-cyber-cyan" />
                        <span className="text-[10px] text-cyber-cyan font-bold uppercase tracking-widest">Protocol Version v2.4.0 (Python)</span>
                    </div>
                    <button 
                      onClick={() => navigator.clipboard.writeText(pythonImplementation)}
                      className="text-[9px] bg-cyber-gray/30 hover:bg-cyber-cyan hover:text-black border border-cyber-gray px-3 py-1.5 rounded-sm transition-all uppercase font-bold"
                    >
                        Copy Implementation
                    </button>
                </div>
                <pre className="text-[11px] text-cyber-green/90 leading-relaxed overflow-x-auto p-5 bg-cyber-black rounded-sm border border-cyber-gray/50 font-mono">
                    {pythonImplementation}
                </pre>
            </div>
        )}
      </div>

      {/* Final Verification Seal */}
      <div className="bg-black/80 backdrop-blur-sm border border-cyber-gray font-mono relative overflow-hidden rounded-sm">
         <div className="absolute top-0 left-0 w-1 h-full bg-cyber-cyan shadow-neon-cyan"></div>
         
         <div className="p-8">
            <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-6 mb-8">
                <div className="bg-cyber-gray px-4 py-2 text-[10px] text-white tracking-[0.2em] uppercase flex items-center gap-3 font-bold">
                    <DollarSign size={12} className="text-cyber-cyan" /> 
                    Audit Telemetry Log
                </div>
                <div className="flex gap-4 print:hidden">
                    <button onClick={handleDownloadAsset} className="flex items-center gap-2 text-[10px] bg-cyber-dark border border-cyber-gray hover:border-cyber-cyan text-slate-400 hover:text-white px-4 py-2 transition-all uppercase tracking-widest font-bold">
                        <Download size={14} /> Download MD Report
                    </button>
                    <button onClick={() => window.print()} className="flex items-center gap-2 text-[10px] bg-cyber-dark border border-cyber-gray hover:border-cyber-red text-slate-400 hover:text-white px-4 py-2 transition-all uppercase tracking-widest font-bold">
                        <Printer size={14} /> Export PDF Dossier
                    </button>
                </div>
            </div>

            <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-4">
                {[
                    { label: "Token Length", value: inputRequest.outputCharCount.toLocaleString(), icon: <MessageSquare size={12}/>, suffix: ' chars' },
                    { label: "Wait Factor", value: inputRequest.apiLatencySeconds, icon: <Timer size={12}/>, suffix: 's' },
                    { label: "Review Tax", value: (inputRequest.editSessionSeconds / 60).toFixed(1), icon: <Clock size={12}/>, suffix: 'm' },
                    { label: "Unit Cost", value: inputRequest.apiCostUsd.toFixed(3), icon: <Cpu size={12}/>, prefix: '$' },
                    { label: "Prod WPM", value: inputRequest.humanWpm, icon: <Keyboard size={12}/> },
                    { label: "Audit WPM", value: inputRequest.humanReadingWpm, icon: <BookOpen size={12}/> },
                    { label: "Wage Rate", value: inputRequest.hourlyWage.toFixed(0), icon: <Briefcase size={12}/>, prefix: '$', suffix: '/hr' }
                ].map(item => (
                    <div key={item.label} className="bg-cyber-dark p-3 border border-cyber-gray/30 group hover:border-cyber-cyan/50 transition-colors">
                        <div className="text-slate-600 uppercase tracking-widest mb-2 flex items-center justify-center gap-2 text-[9px] group-hover:text-cyber-cyan transition-colors">{item.icon} {item.label}</div>
                        <div className="text-sm text-white font-bold text-center">
                            {item.prefix}{item.value}{item.suffix}
                        </div>
                    </div>
                ))}
            </div>
         </div>

         {/* Disclaimer Footer */}
         <div className="border-t border-cyber-gray bg-cyber-dark/60 p-6 flex flex-col md:flex-row items-center justify-center gap-8">
            <div className="flex items-center gap-4 px-5 py-3 bg-cyber-green/5 border border-cyber-green/20 rounded-sm">
                <ShieldCheck size={24} className="text-cyber-green drop-shadow-glow-green animate-pulse" />
                <div>
                    <span className="text-[11px] font-bold text-white uppercase tracking-[0.2em] block">Verified Audit Status: ACTIVE</span>
                    <span className="text-[9px] text-cyber-green/70 font-bold uppercase tracking-widest">Deterministic Accounting Logged</span>
                </div>
            </div>
            
            <div className="flex-1 max-w-xl">
                <p className="text-[9px] text-slate-500 uppercase tracking-widest text-center md:text-left leading-relaxed italic">
                    <strong className="text-slate-400 not-italic">DISCLAIMER:</strong> This report constitutes a mathematical valuation of operational labor displacement. Arbitrage is calculated based on linear manual production physics vs recorded interaction friction. Final results are verified for enterprise BI integration.
                </p>
            </div>

            <div className="flex flex-col items-end gap-1 text-[9px] text-slate-600 font-bold">
                <div className="flex items-center gap-2">
                    <Fingerprint size={12} />
                    <span>UID: {watermark}</span>
                </div>
                <span>TS: {timestamp}Z</span>
            </div>
         </div>
      </div>
    </div>
  );
};

export default DLAResult;
